services:
  python:
    image: iki_project_2026:1.0
    build: ./
    container_name: 'iki_project_2026'
    ports: 
      - 5001:5001
    working_dir: '/project/programs'
    volumes:
      - ../:/project/
    command: tail -f /dev/null
  nginx:
    image: iki_project_2026_nginx
    build: ./nginx/
    container_name: 'iki_project_2026_nginx'
    ports:
      - 8080:80
      - 4430:443
    volumes:
      - ./nginx/ssl/:/etc/nginx/certs/
      - ../:/project/
